### ISSUE TITLE
Error: Cannot find module 'F:\rust\RustPlusBot\tools\external\rustplusDiscordBot.js'

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/RustPlus-Discord-Bot#8]
npm install

```
up to date, audited 248 packages in 5s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

node rustplusDiscordBot.js
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'F:\rust\RustPlusBot\tools\external\rustplusDiscordBot.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Comment by alexemanuelol** [comment]
Executed in the wrong folder? That was the problem?

In case you want something more up to date, take a look at my bot version 2, doesn't have smart devices implemented yet but it's way cleaner than this one.

https://github.com/alexemanuelol/rustPlusPlus

**Comment by Owned67** [comment]
yes, wrong folder xD

Thanks very much
